### ISSUE TITLE
Invalid property recommended for Tomcat context ROOT.xml

### ISSUE THREAD

**Issue by alanorth** [TGAC/miso-lims#1214]
The [admin manual](https://tgac.github.io/miso-lims/manuals/admin-manual.html) recommends the use of `debug="1"` in the Tomcat `ROOT.xml` context for the MISO web application. This causes the following warning to be printed to Tomcat's logs:

```
WARNING: [SetContextPropertiesRule]{Context} Setting property 'debug' to '1' did not find a matching property
```

This is not fatal but nevertheless seems to be ignored by Tomcat and should be probably removed from the documentation.

*Edit: Tomcat version tested was 8.0.32 on Ubuntu 16.04.*

**Comment by callunity** [comment]
Thanks for this, @alanorth . I've updated the [admin manual](https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-admin-manual.md).

(Due to how this project is set up the change isn't visible on the page you linked, but the link I posted above is current, and the readme has also been updated to point to the current link.)
