### ISSUE TITLE
MISO config: miso.properties

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1232]
In our old installation we have configured the naming like this:
```
miso.naming.scheme.nameable:AllowAnythingEntityNamingScheme
miso.naming.scheme.sample:AllowAnythingEntityNamingScheme
miso.naming.scheme.library:AllowAnythingEntityNamingScheme

# mpimg_S11519_CD1WTFLE9-5Rep2
# mpg_S11549_H-O-2
miso.naming.validation.alias.sample:([A-z0-9]+)_S([A-z0-9]+)_(.*)

# ext_L11604-1_4074-D4KO-Heart
# mpimg_L10941-2_870
miso.naming.validation.alias.library:([A-z0-9]+)_L([A-z0-9]+)-([0-9]+)_(.*)
```

The new naming rules are described here ("Naming Schemes"),
https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2016-01-11-admin-manual.md

This is probably more flexible but the description is very formal.

How does our (old) naming configuration translate into the new one?<br>
Also a (detailed) description of the options would be nice, as this is very fundamental and must be understood and setup before starting a/the LIMS in production...

**Comment by djcooke** [comment]
The default naming scheme (`miso.naming.scheme:default`) has those settings, so this is the only property you'll have to set for naming scheme. You don't have to configure any name generators or validators separately.

All of the options have brief descriptions within the `miso.properties` file. The naming schemes are detailed further in the admin manual because of the many options. Are there any other settings that you'd like more details about?

**Comment by sklages** [comment]
Thanks. That's straight forward using `miso.naming.scheme:default`. I was not really sure about all the other (naming) paramaters mentioned. 👍 

`miso.detailed.sample.enabled` is an OICR specific thingy? When using their naming conventions?

AFAICS all other parameters are clear to me or not of interest yet :-)

**Comment by djcooke** [comment]
Detailed sample expands samples into a hierarchy of tissues, stocks, aliquots, etc., and adds several related attributes. It was designed to meet OICR's needs, but I wouldn't say it is OICR-specific. It would not be compatible with your existing data, however.
