### ISSUE TITLE
Feature Request: extend max index length to >35

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1248]
Index length is currently restricted to 24 chars.

10x Genomics Single Cell 3' Sequencing uses sets of four indices, e.g.
```
SI-GA-A1,GGTTTACT,CTAAACGG,TCGGCGTC,AACCGTAA
[..]
SI-GA-H12,GACAGCAT,TTTGTACA,AGGCCGTG,CCATATGC
```
Demultiplexing of such sets is done by [10x Genomics custom software](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/mkfastq), only using sample IDs and indexset name.

Nevertheless it would be useful to have the index sequences included too.

```
CALL addIndexFamily('10x Genomics Single Cell 3p', 'ILLUMINA', 0);
CALL addIndex('10x Genomics Single Cell 3p', 'SI-GA-A1', 'GGTTTACT-CTAAACGG-TCGGCGTC-AACCGTAA', 1);
[..]
CALL addIndex('10x Genomics Single Cell 3p', 'SI-GA-H12', 'GACAGCAT-TTTGTACA-AGGCCGTG-CCATATGC', 1);
```
fails because of length restriction.

Also index name is restricted to 10 chars, which can also be too small (in future), e.g. `SI-GA-H12` has already nine chars.

**Comment by djcooke** [comment]
There isn't a great way to represent these in MISO currently. We have entered the index name (e.g. 'SI-GA-A1') as both the name and sequence. As you mentioned, this is all the software needs to demultiplex them.

We can probably change the field length anyway, but until that change goes through, there shouldn't be any harm in modifying the length in your own database:

```
ALTER TABLE Indices CHANGE COLUMN name name varchar(48) NOT NULL;
ALTER TABLE Indices CHANGE COLUMN sequence sequence varchar(48) NOT NULL;
```

Note that since the name and sequence are shown in the dropdown for indices when bulk editing Libraries, long names/sequences like these will cause the column/dropdown to be very wide

**Comment by sklages** [comment]
That's what I thought too, alternatively put in names into the sequence field. Or at least the first index..

I'll probably give it a try changing the lengths in the database and see how it works out.

**Comment by sklages** [comment]
I altered the `name` and `sequence` lengths and asked the lab staff which "sequence" should show up. 
All want the complete index set to show up, even in bulk library creation .. it's not too wide, we have large monitors ;-)

**Comment by sklages** [comment]
Works like a charm.
