### ISSUE TITLE
Library alias naming / pattern recognition

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1278]
```
# ([A-z0-9]+)_S([A-z0-9]+)_(.*)
miso.naming.scheme:default
```

Given name: `mpimg_S11670_91_FL-Bl6`

Parts: `mpimg | S11670 | 91_FL-Bl6`

After creating a library from this sample we get:

`mpimg_L11670_91-2_FL-Bl6`

Parts: `mpimg | L11670_91-2 | FL-Bl6`

We usually do not allow for underscores "_" in sample names.

Nevertheless I think this behavior of creating the library alias is wrong.

Instead of `mpimg_L11670_91-2_FL-Bl6` I would expect to get `mpimg_L11670-2_91_FL-Bl6` (right after the second part).

**Comment by djcooke** [comment]
This has been the pattern of the default library alias generator for a long time, and changing it now could be disruptive to others who have been using it. You could write a new library alias generator with the desired behaviour:
* copy `DefaultLibraryAliasGenerator`
* make the changes you'd like
* add it as an option in `StaticMappedNamingSchemeResolverService`

**Comment by sklages** [comment]
I probably won't need it. It's just that from the sample pattern I would expect the library counter at a different location.

We do not allow for underscores in sample names. I suspect "_"  triggers this "behavior".

**Comment by djcooke** [comment]
It is the underscore which is causing a name that you wouldn't expect. This is because the character range "A-z" will contain A-Z and a-z, but also these character: ``[\]^_` `` (check the utf8 character table). While I'm not sure this was intentional, it is established.

Your policy of not including these characters is a good one though!
