### ISSUE TITLE
Edit Samples: <Prev Next> not working properly

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1324]
When editing a sample, the "< Previous Sample XXX" and "Next Sample YYY>" navigation elements are not working properly.

E.g.

I am switching to "Edit sample SAM7870".

I shows `Previous Sample SAM6996` and `Next Sample SAM7860`. That's not correct.

When Pressing `Next Sample SAM7860` it goes to "SAM7860",  `Previous Sample SAM6996`  is still unchanged. When pressing `Previous Sample SAM6996` it is opening the edit page for "SAM6996", ok.

Previous is now "SAM6995", Next is now "SAM7859".

I would have expected on the initial page to go to "SAM7871" with "Next" and "SAM7869" with "Previous".

You know what I mean?

**Comment by djcooke** [comment]
The previous and next samples won't always be current sampleId +/- 1 as they are constrained to samples within the same project. e.g.

SAM100 belongs to PRO1 <-- previous sample
SAM101 belongs to PRO2
SAM102 belongs to PRO1 <-- user is on this page
SAM103 belongs to PRO2
SAM104 belongs to PRO1 <-- next sample

That said, there are cases where the previous/next sample can end up being wrong. Will fix this for the next release

**Comment by sklages** [comment]
OK, yes you're, that's good though ;-)
But in this case all "surrounding" samples belong to the same project, 7859 to 7894.  "SAM6996" also belongs to this project.

**Comment by sklages** [comment]
The same seems to be valid for libraries as well.

**Comment by djcooke** [comment]
Fixed Samples' ordering in PR.

I don't think there is a problem with Libraries. The sort order is less obvious though - The primary sort key is the **sample** ID rather than the library ID. e.g.

LIB1 is child of SAM1
LIB2 is child of SAM2
LIB3 is child of SAM1
LIB4 is child of SAM3
LIB5 is child of SAM2
LIB6 is child of SAM1

Sort order of these for the purpose of prev/next buttons is LIB1, LIB3, LIB6, LIB2, LIB5, LIB4:

* SAM1 libraries: LIB1, LIB3, LIB6
* SAM2 libraries: LIB2, LIB5
* SAM3 library: LIB4

Does there still seem to be a problem with Libraries?

**Comment by sklages** [comment]
hmm, .. yes. We are struggling a bit with the "logic" of bulk library creation.
When I have "SAM1" to "SAM10" and I bulk create libraries for these samples, I would expect the LIB-IDs to be in the same order as the samples, not necessarily the same number, but in the same order.
This seems to be true for most libs, but not for all? There are libs from the bulk creation that get other numbers, not in the order I would expect ...

I have to check this a bit more in detail ....

**Comment by djcooke** [comment]
Library IDs are not guaranteed to be generated in the order that you are expecting. IDs are used for a rough ordering, but are intended for identification purposes only

**Comment by sklages** [comment]
ok, interesting.
We are usually working "in order". That works pretty fine with samples (after bugfixing), but is somewhat hard with "unordered" libraries. Mainly because we document some QCs things on that level. So it's not simply the next lib we can switch to, we need to go back to libs page, search for the lib of interest, edit the lib of interest. That's a bit laborious.

So maybe Prev/Next can work on the corresponding **aliases** instead of the name (IDs), for both samples and libraries? 
ID handling would not be touched, Prev/Next usability would be optimized. :-)

**Comment by djcooke** [comment]
Others (Earlham Institute for sure) depend on the existing ordering of these prev/next buttons. Sorting by alias will have unpredictable and likely stranger results, as it would depend on the naming scheme.

Depending on what exactly you're trying to do, might you be able to use the bulk Edit Libraries or bulk Add QCs pages rather than navigating using prev/next?

**Comment by sklages** [comment]
I have to check that with the lab people, as they are actually using MISO in daily production routine.

**Comment by sklages** [comment]
This goes back to issue #1243 . Would be nice to be able to create notes in sample/library bulk creation (again).

**Comment by djcooke** [comment]
Would the proposed solution in #1243 solve the underlying problem here?

**Comment by sklages** [comment]
Yes, it would.

**Comment by djcooke** [comment]
Closing this ticket then, as the original issue has been fixed/explained. Feel free to reopen if there is an aspect of this issue that has not been addressed either here or in #1243
