### ISSUE TITLE
Feature Request: "Index Distance" should also consider stored indices

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1357]
`Index Distance` is a nice and helpful tool when dealing with new / unknown indices.

It would be even more helpful if it would additionally/optionally scan the indices of interest against known selectable `Index Family` from the miso database.

When entering 6nt indices, it should be possible to check these against the first 6 bases of longer index sequences (especially 8nt indices) as quite some people mix 6nt and 8nt indices on a single lane.

It would make it somehow "complete" .. just an idea :-)

**Comment by djcooke** [comment]
Hi Sven, thanks for the feedback.

For your first request, it is possible to search the table below by the index family name, then select all and add to the list.

For your second, only the length of the shortest index is considered. 'AAAAAA' and 'AAAAAACC' are considered duplicates, for example, because only the first 6 bases are compared. Check the _Quick Help_ drop-down on the page for more info.

Do these achieve what you're asking?

**Comment by sklages** [comment]
Ha, sure, that's it!
The Quick Help hasn't been used that often in the past .. now I will always read that before asking :-)

thanks, "solved".
