### ISSUE TITLE
Q: Sample Workflow / Orders

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1385]
Due to some discussions here in the lab, I have a few questions concerning sample receiving etc.

1. How does your practical (Lab->MISO) workflow look like when you receive samples? 
E.g. a customer has some tissues and want to finally get a HiSeq 4000 DNAseq lane. When do you enter the samples in MISO, how do you enter the samples in MISO? I am particularly unsure about `Receive Samples` and `Import & Export` in the navigation pane (we do not use it yet) as this is not really documented very well (real life examples and "terminology").
We are still using a bunch of Excel tables outside of MISO for tissue/sample receiving and register sample data in MISO when the samples are actually "in work".

1. how do you keep a good "overview" of which libraries can be pooled on a large flowcell, e.g. NovaSeq's S4? I assume that this is what `Orders` are for? Again, here the lab still uses Excel tables outside MISO. 

I just want to get an idea if we can "optimize" certain partial workflows in our "total" workflow ...

**Comment by djcooke** [comment]
1. At OICR, we use the "detailed sample" mode of MISO, which involves a larger hierarchy of "samples" and includes different information relating to donors, tissues, aliquots, and some other sample processing steps. Whatever we receive gets entered into MISO. Whenever we work with those samples, the resulting downstream products get entered into MISO. We do not use the `Receive Samples` or `Import & Export` features; we've actually hidden these options on our production MISO.

@froggleston may have a better answer regarding those features, as well as using MISO in plain sample mode.

2. I don't think there's a way to indicate "which libraries can be pooled on a large flowcell" in MISO since Orders are at the Pool level, and not the Library level. Our libraries team creates an Order when they have a Pool ready for sequencing.
