### ISSUE TITLE
Q: Container Model = Unknown 8-Lane Illumina Flow Cell

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1493]
I see that our HiSeq flowcells are of type `Container Model=Unknown 8-Lane Illumina Flow Cell`, our NextSeq500 `Container Model=Unknown 4-Lane Illumina Flow Cell` and so on. 

I had a look in `SequencingContainerModel` to see where it comes from.
Is it as simple as just changing the assignments in `SequencingContainerModel_Platform` to  correct the container models?

**Comment by callunity** [comment]
Hi @sklages ,
The "Unknown X-Lane Illumina Flow Cell" SequencingContainerModels are used as defaults when no other sequencing container models can be found. During the migration that added all of the SequencingContainerModels, the existing containers were all associated with default "Unknown" container models. You can add specific container models to your database and runscanner will update them. At the [bottom of this page](https://github.com/TGAC/miso-lims/blob/develop/docs/_posts/2017-12-07-admin-guide.md) there is a **List of Container Models** that we've found at our institute, and you could add any or all of those. You'll need to first add [this procedure](https://github.com/TGAC/miso-lims/blob/develop/sqlstore/src/main/resources/db/migration_beforeMigrate/05__add_containermodel.sql) to your database in order to be able to add those container models.
