### ISSUE TITLE
Q: Attachments - Download "Behavior"

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1601]
It is now possible to attach files to e.g. runs.
I will use this feature to upload static HTML files containing (our own) demultiplexing statistics for the corresponding run. That "finalizes" the sample tracking here :smile:

Downloading such attachments is done by ID, e.g. `http://my.miso/miso/attachments/run/537/1`. In my case, the HTML is downloaded. 
What I would like to achieve is, when downloading a certain document type from MISO that the corresponding program is opened. E.g when download a HTML file, I would like to see it rendered in a new tab...

Is there a way to (easily) accomplish this?

**Comment by sklages** [comment]
That probably applies to standard formats like PDF, XLS(X) and maybe some others as well.

**Comment by djcooke** [comment]
The attachments can't (easily) be served as regular web pages, and I don't think we would want them to be, as some people would prefer to download them. Your browser likely allows the behaviour you're asking for though.

* When downloading an HTML file in Firefox, you should have the options 'Open with' and 'Save file.' In the 'Open with' options, you can choose Firefox. There's also a 'Do this automatically for files like this from now on' checkbox, so that you don't have to select the option every time.

* After downloading an HTML file in Chrome, you can click the '...' button and choose 'Always open files of this type'

**Comment by sklages** [comment]
Sure, you are right. That's just as simple. I haven't thought about that :+1:
