### ISSUE TITLE
Library Templates: Server Error

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1670]
I wanted to find out what is `Library Templates` for.

`Add` resulted in an error: `An unexpected error has occurred. If the problem persists, please report it to your MISO administrators`

The `miso_debug.log` states:
```
2018-09-20 14:42:41 ERROR: Returning error page for exception
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""
```
This is MISO `Version: 0.2.140`.

**Comment by djcooke** [comment]
Library Templates are a collection of properties that you can apply to new Libraries so that you don't have to choose all of the properties individually.

I haven't been able to produce the same error as you posted above, though I did find another related bug while trying. Could you explain how exactly it happened? e.g. "Go to project page, click 'Add' in the Library Templates section, enter '1' in the dialog and press 'Create'"

It would also be helpful if you could share the entire stack trace from `miso_debug.log`

Thanks

**Comment by sklages** [comment]
Well I just finished updating to `0.2.141` and now `Library Templates` is working as intended  AFAICS.

**Comment by djcooke** [comment]
There were still two issues that I found in v0.2.142 (not yet officially released)

* When trying to save a Library Template with no project (created form the Library Templates list page), save failed due to NullPointerException
* Choosing 'Add' (Library Templates) and then clearing the quantity value in the dialog produced an error instead of stating that the quantity is required

Both fixed in PR
