### ISSUE TITLE
ERROR: Wrong migration name format: V88977_watch.sql

### ISSUE THREAD

**Issue by sklages** [TGAC/miso-lims#1796]
I ran into the problem tagged as "Bad:" in latest `v0.2.158`:
```
Flyway 3.2.1 by Boxfuse

Database: jdbc:mysql://localhost:3307/miso_seqcore (MySQL 5.7)
ERROR: Wrong migration name format: V88977_watch.sql
(It should look like this: V1_2__Description.sql)
```
As I didn't know how to fix it I restored the database and recompiled `v0.2.158`.
For the next version: Can I directly build `v0.2.159` (or whatever version is approbiate)?
Or is there a way (for me) to fix this in `v0.2.158`?

**Comment by djcooke** [comment]
v0.2.158 was not flagged as a release due to this issue. To ensure that you don't deploy unstable versions, I'd suggest using official releases only. The [Releases](https://github.com/TGAC/miso-lims/releases) page unfortunately shows all tagged versions, but the official releases are the ones which have a larger title and change log included. The last official release was v0.2.154.

If you've already upgraded beyond v0.2.154 and can't go back at this point, v0.2.159 should be fine too. We have been using v0.2.159 in production for almost a week at OICR. Normally, we run a version in both our staging and production environments for at least a week before marking it as a release.

**Comment by sklages** [comment]
Hmm, okay. I didn't notice that these were not official releases. Usually I do install official releases only. 
I am currently on version v0.2.157... is it safe to stick with that version? Or shall I upgrade to v0.2.159?

**Comment by djcooke** [comment]
v0.2.157 had a bug where runs reported by Run Scanner were not being saved correctly. v0.2.159 would be preferable as there are still no known issues with it

**Comment by sklages** [comment]
Oh well, I didn't check the release page, I just read the release notes. Latest version there is v0.2.158. 
v0.2.159 compiled & migrated just fine .. thanks.

Time for X-mas break ;-)

**Comment by djcooke** [comment]
Happy holidays!
